version: "3"
services:
  postgres:
          image: postgres:latest
          container_name: postgres
          ports:
              - "5432:5432"
          environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: loizenaidb
  backend:
    image: srikavyapendiala/backend:latest
    container_name: backend
    environment:
      database: loizenaidb
      username: postgres
      password: 123
      host: postgres
      dialect: postgres
    ports:
        - "8080:8080"
    depends_on:
          - postgres

  frontend:
          image: srikavyapendiala/frontend:latest
          container_name: frontend
          stdin_open: true
          environment: 
            - backend=localhost
          ports:
                - "3000:3000"
          depends_on:
                - backend
