version: "3.3"
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: loizenaidb
 
  backend:
    image: srikavyapendiala/backend:v1
    container_name: backend
    ports:
      - "8080:8080"

    depends_on:
      - postgres
    environment:
      BACKEND_DATA: loizenaidb
      BACKEND_USER: postgres
      BACKEND_PASS: 123
      BACKEND_HOST: postgres
    

  frontend:
    image: srikavyapendiala/frontend:v1
    container_name: frontend
    stdin_open: true
    environment:
           proxy: backend
    ports:
      - "3000:3000"

    depends_on:
      - backend

 
